theme: jekyll-theme-dinky

# Site Settings
locale                   : "es-ES"
title                    : "Midiendo la web"
title_separator          : "|"
name                     : "Emirodgar"
twitter_username: emirodgar
github_username:  emirodgar
