#theme: jekyll-theme-dinky
remote_theme: mmistakes/minimal-mistakes

# Site Settings
locale                   : "es-ES"
title                    : "Midiendo la web - Libro online gratuito sobre estrategias digitales"
title_separator          : "-"
name                     : "Emirodgar"
