#theme: jekyll-theme-dinky
remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll

# Site Settings
locale                   : "es-ES"
title                    : "Midiendo la web"
title_separator          : "|"
name                     : "Emirodgar"
